### ISSUE TITLE
After you delete a message it still shows

### ISSUE THREAD

**Issue by Hamy-os** [iodineimg/dashboard-bugs#5]
as tittle shows when you click the delete button it says it was deleted but is still there and accesible

**Comment by wowjeeez** [comment]
yes, this is related to #1

**Comment by wowjeeez** [comment]
*A refresh should solve it

**Comment by Hamy-os** [comment]
> *A refresh should solve it

but it doesnt. the image is still there

**Comment by wowjeeez** [comment]
yes, I tested now I will look into it.

**Comment by wowjeeez** [comment]
Fixed on latest deployment
