### ISSUE TITLE
if a image hasnt been previously opened the resolution wont show 

### ISSUE THREAD

**Issue by Hamy-os** [iodineimg/dashboard-bugs#7]

**Comment by Hamy-os** [comment]
the resolution is also falsely calculated. tested with a 577 x 81 image dash showed 384x54

**Comment by wowjeeez** [comment]
> tested with a 577 x 81 image dash showed 384x54
CSS resizing

**Comment by wowjeeez** [comment]
> the resolution is also falsely calculated. tested with a 577 x 81 image dash showed 384x54
Fixed in latest redeploy
