### ISSUE TITLE
Copy to clipboard non-functional on iOS

### ISSUE THREAD

**Issue by n0tsiege** [iodineimg/dashboard-bugs#8]
After uploading, copying to clipboard (as the notification claims) does not work and the URL is nowhere to be found.
Steps to reproduce:
Login to dash on mobile
Go to upload tab
Upload image
Attempt to paste 

Expected result: Image url pastes
Given result: Clipboard is empty, no url

Device Info:
iPhone XR
iOS 14.6

**Comment by n0tsiege** [comment]
It does appear that the copy to clipboard on the Images page does work, although this is with the click of a button rather than with the upload.

**Comment by wowjeeez** [comment]
Seems to work on Android, we will look into it

**Comment by n0tsiege** [comment]
could always be an iOS issue - thanks for investigating. iodine best.

**Comment by wowjeeez** [comment]
I will take this as a "working" solution for now, will check back later
